[serviceweaver]
name = "calc"
binary = "cmd/cmd"

["github.com/ServiceWeaver/weaver/Main"]
multiplier_addr = "multiplier:8000"

[kube]
listeners.calc = { public = true, service_name = "calc" }
image = "calc:3b"
repo = "docker.io/themwhittaker"
