apiVersion: v1
kind: ConfigMap
metadata:
  name: adder-config
data:
  weaver.toml: |
    [serviceweaver]
    name = "adder"

    [single]
    listeners.adder = {address = ":8000"}

---
apiVersion: v1
kind: Service
metadata:
  name: calc
spec:
  selector:
    app: calc
  ports:
  - port: 8000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: adder
spec:
  selector:
    app: adder
  ports:
  - protocol: TCP
    port: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: multiplier
spec:
  selector:
    app: multiplier
  ports:
  - protocol: TCP
    port: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc
spec:
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc
        image: themwhittaker/calc:2
        imagePullPolicy: Always
        args: ["--addr=:8000", "--adder=adder:8000", "--multiplier=multiplier:8000"]
        ports:
        - containerPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adder
spec:
  selector:
    matchLabels:
      app: adder
  template:
    metadata:
      labels:
        app: adder
    spec:
      containers:
      - name: adder
        image: themwhittaker/adder:3
        imagePullPolicy: Always
        env:
        - name: SERVICEWEAVER_CONFIG
          value: "/app/weaver.toml"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: config
          mountPath: /app/weaver.toml
          subPath: weaver.toml
      volumes:
      - name: config
        configMap:
          name: adder-config
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplier
spec:
  selector:
    matchLabels:
      app: multiplier
  template:
    metadata:
      labels:
        app: multiplier
    spec:
      containers:
      - name: multiplier
        image: themwhittaker/multiplier:3
        imagePullPolicy: Always
        args: ["--addr=:8000"]
        ports:
        - containerPort: 8000
